"""Embeds the sound files of assets/ into src/sounds_gen.js as base64 data (the game is a single file)."""
import base64, os
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.join(HERE, "..")
FILES = {"SKRICHUSHKA_BREAK": "skrichushka_break.mp3"}
out = ["// GENERATED by tools/make_sounds.py — do not edit"]
for name, fn in FILES.items():
    data = open(os.path.join(ROOT, "assets", fn), "rb").read()
    out.append(f'const SOUND_{name} = "data:audio/mpeg;base64,{base64.b64encode(data).decode()}";')
open(os.path.join(ROOT, "src", "sounds_gen.js"), "w").write("\n".join(out) + "\n")
print("sounds_gen.js", len(out) - 1, "sound(s)")
