"""Generates src/assets_gen.js: pixel font atlas (Latin + Cyrillic) and a pixel world-map land mask.

Land polygons: Natural Earth 110m (public domain). Font: DejaVu Sans Bold, rasterised at 4x and
box-downsampled + thresholded so every glyph is crisp pixel art.
Usage: python tools/make_assets.py
"""
import base64, io, json, math, os
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "src", "assets_gen.js")
FONT = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"
SIZES = [8, 10, 14, 22]
CHARS = [chr(c) for c in range(32, 127)] + [chr(c) for c in range(0x410, 0x450)] + ["Ё", "ё"] + list("—–·…×→←↑↓♥✓•°«»№’“”±≈½©★▪✕›")

def glyph(font4, ch, size):
    l, t, r, b = font4.getbbox(ch, anchor="ls")
    adv = font4.getlength(ch) / 4.0
    if ch == " ":
        return None, max(2, round(adv)), 0, 0
    py = int(math.ceil(-t / 4)) + 1
    cw = int(math.ceil((8 + r + 8) / 4)) * 4
    ch_ = int(math.ceil((4 * py + b + 8) / 4)) * 4
    big = Image.new("L", (cw, ch_), 0)
    ImageDraw.Draw(big).text((8, 4 * py), ch, font=font4, fill=255, anchor="ls")
    small = big.resize((cw // 4, ch_ // 4), Image.BOX).point(lambda v: 255 if v > 80 else 0)
    bb = small.getbbox()
    if not bb:
        return None, max(2, round(adv)), 0, 0
    crop = small.crop(bb)
    xoff = bb[0] - 2           # pen starts at x=2 in the small image
    yoff = bb[1] - py          # relative to baseline
    return crop, max(1, round(adv)), xoff, yoff

def build_font():
    atlas = Image.new("RGBA", (1024, 256), (0, 0, 0, 0))
    meta = {}
    cx = cy = rowh = 0
    for size in SIZES:
        f4 = ImageFont.truetype(FONT, size * 4)
        f1 = ImageFont.truetype(FONT, size)
        asc = f1.getmetrics()[0]
        meta[size] = {"asc": asc, "lh": round(size * 1.35), "g": {}}
        for ch in CHARS:
            img, adv, xo, yo = glyph(f4, ch, size)
            if img is None:
                meta[size]["g"][ch] = [0, 0, 0, 0, adv, 0, 0]
                continue
            w, h = img.size
            if cx + w + 1 > 1024:
                cx, cy, rowh = 0, cy + rowh + 1, 0
            rgba = Image.new("RGBA", (w, h), (255, 255, 255, 0))
            rgba.putalpha(img)
            rgba.paste((255, 255, 255, 255), mask=img)
            atlas.paste(rgba, (cx, cy))
            meta[size]["g"][ch] = [cx, cy, w, h, adv, xo, yo]
            cx += w + 1
            rowh = max(rowh, h)
        cx, cy, rowh = 0, cy + rowh + 1, 0
    atlas = atlas.crop((0, 0, 1024, cy + 1))
    buf = io.BytesIO()
    atlas.save(buf, "PNG", optimize=True)
    return meta, "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()

# ---- world map -------------------------------------------------------------
MAP_W, MAP_H = 200, 77
LAT_TOP, LAT_BOT = 80.0, -58.0
SS = 8

def build_map():
    gj = json.load(open(os.path.join(HERE, "data", "ne_110m_land.geojson")))
    big = Image.new("L", (MAP_W * SS, MAP_H * SS), 0)
    d = ImageDraw.Draw(big)
    def proj(lon, lat):
        return ((lon + 180) / 360 * MAP_W * SS, (LAT_TOP - lat) / (LAT_TOP - LAT_BOT) * MAP_H * SS)
    for feat in gj["features"]:
        g = feat["geometry"]
        polys = g["coordinates"] if g["type"] == "MultiPolygon" else [g["coordinates"]]
        for poly in polys:
            for i, ring in enumerate(poly):
                d.polygon([proj(x, y) for x, y in ring], fill=255 if i == 0 else 0)
    small = big.resize((MAP_W, MAP_H), Image.BOX).point(lambda v: 1 if v > 110 else 0)
    px = small.load()
    rows = []
    for y in range(MAP_H):
        bits = "".join(str(px[x, y]) for x in range(MAP_W))
        rows.append(bits)
    return rows

if __name__ == "__main__":
    meta, png = build_font()
    rows = build_map()
    with open(OUT, "w") as f:
        f.write("// GENERATED by tools/make_assets.py — do not edit\n")
        f.write("const FONT_META = " + json.dumps(meta, ensure_ascii=False) + ";\n")
        f.write("const FONT_PNG = " + json.dumps(png) + ";\n")
        f.write(f"const MAP_W = {MAP_W}, MAP_H = {MAP_H}, MAP_LAT_TOP = {LAT_TOP}, MAP_LAT_BOT = {LAT_BOT};\n")
        f.write("const MAP_ROWS = " + json.dumps(rows) + ";\n")
    print("wrote", OUT, os.path.getsize(OUT) // 1024, "KB")
